;;; $DOOMDIR/lisp/nerd-icons-treemacs-theme.el -*- lexical-binding: t; -*-

;; Setting fallback instead of icon because :fallback 'same-as-icon throws an error

(require 'nerd-icons)
(require 'treemacs)

(defface treemacs-nerd-icons-root-face
  '((t (:inherit font-lock-string-face)))
  "Face used for the root icon in nerd-icons theme."
  :group 'treemacs-faces)

(defface treemacs-nerd-icons-file-face
  '((t (:inherit font-lock-doc-face)))
  "Face used for the directory and file icons in nerd-icons theme."
  :group 'treemacs-faces)

(defvar treemacs-nerd-icons-tab (if (bound-and-true-p treemacs-nerd-icons-tab-font)
                                    (propertize "\t" 'face `((:family , treemacs-nerd-icons-tab-font)))
                                  "\t"))

(treemacs-create-theme "nerd-icons"
  :config
  (progn
    ;; directory and other icons
    (treemacs-create-icon :fallback (format "%s%s" (nerd-icons-octicon "repo" :height 1.2 :v-adjust -0.1 :face 'treemacs-nerd-icons-root-face) treemacs-nerd-icons-tab)
                          :extensions (root-closed root-open)
                          :icon "")
    (treemacs-create-icon :fallback (format "%s%s%s%s"
                                        (nerd-icons-faicon "chevron-circle-down" :height 0.75 :v-adjust 0.1 :face 'treemacs-nerd-icons-file-face)
                                        treemacs-nerd-icons-tab
                                        (nerd-icons-octicon "file-directory" :v-adjust 0 :face 'treemacs-nerd-icons-file-face)
                                        treemacs-nerd-icons-tab)
                          :extensions (dir-open)
                          :icon "")
    (treemacs-create-icon :fallback (format "%s%s%s%s"
                                        (nerd-icons-faicon "chevron-circle-right" :height 0.75 :v-adjust 0.1 :face 'treemacs-nerd-icons-file-face)
                                        treemacs-nerd-icons-tab
                                        (nerd-icons-octicon "file-directory" :v-adjust 0 :face 'treemacs-nerd-icons-file-face)
                                        treemacs-nerd-icons-tab)
                          :extensions (dir-closed)
                          :icon "")
    (treemacs-create-icon :fallback (format "%s%s%s%s"
                                        (nerd-icons-faicon "chevron-circle-down" :height 0.75 :v-adjust 0.1 :face 'treemacs-nerd-icons-file-face)
                                        treemacs-nerd-icons-tab
                                        (nerd-icons-octicon "package" :v-adjust 0 :face 'treemacs-nerd-icons-file-face)
                                        treemacs-nerd-icons-tab)
                          :extensions (tag-open)
                          :icon "")
    (treemacs-create-icon :fallback (format "%s%s%s%s"
                                        (nerd-icons-faicon "chevron-circle-right" :height 0.75 :v-adjust 0.1 :face 'treemacs-nerd-icons-file-face)
                                        treemacs-nerd-icons-tab
                                        (nerd-icons-octicon "package" :v-adjust 0 :face 'treemacs-nerd-icons-file-face)
                                        treemacs-nerd-icons-tab)
                          :extensions (tag-closed)
                          :icon "")
    (treemacs-create-icon :fallback (format "%s%s" (nerd-icons-octicon "tag" :height 0.9 :v-adjust 0 :face 'treemacs-nerd-icons-file-face) treemacs-nerd-icons-tab)
                          :extensions (tag-leaf)
                          :icon "")
    (treemacs-create-icon :fallback (format "%s%s" (nerd-icons-octicon "flame" :v-adjust 0 :face 'nerd-icons-red) treemacs-nerd-icons-tab)
                          :extensions (error)
                          :icon "")
    (treemacs-create-icon :fallback (format "%s%s" (nerd-icons-octicon "stop" :v-adjust 0 :face 'nerd-icons-yellow) treemacs-nerd-icons-tab)
                          :extensions (warning)
                          :icon "")
    (treemacs-create-icon :fallback (format "%s%s" (nerd-icons-octicon "info" :height 0.75 :v-adjust 0.1 :face 'nerd-icons-blue) treemacs-nerd-icons-tab)
                          :extensions (info)
                          :icon "")
    (treemacs-create-icon :fallback (format "%s%s" (nerd-icons-octicon "mail" :height 0.75 :v-adjust 0.1 :face 'treemacs-nerd-icons-file-face) treemacs-nerd-icons-tab)
                          :extensions (mail)
                          :icon "")
    (treemacs-create-icon :fallback (format "%s%s" (nerd-icons-octicon "bookmark" :height 0.75 :v-adjust 0.1 :face 'treemacs-nerd-icons-file-face) treemacs-nerd-icons-tab)
                          :extensions (bookmark)
                          :icon "")
    (treemacs-create-icon :fallback (format "%s%s" (nerd-icons-material "monitor" :height 0.75 :v-adjust 0.1 :face 'treemacs-nerd-icons-file-face) treemacs-nerd-icons-tab)
                          :extensions (screen)
                          :icon "")
    (treemacs-create-icon :fallback (format "%s%s" (nerd-icons-material "home" :height 0.75 :v-adjust 0.1 :face 'treemacs-nerd-icons-file-face) treemacs-nerd-icons-tab)
                          :extensions (house)
                          :icon "")
    (treemacs-create-icon :fallback (format "%s%s" (nerd-icons-material "menu" :height 0.75 :v-adjust 0.1 :face 'treemacs-nerd-icons-file-face) treemacs-nerd-icons-tab)
                          :extensions (list)
                          :icon "")
    (treemacs-create-icon :fallback (format "%s%s" (nerd-icons-material "repeat" :height 0.75 :v-adjust 0.1 :face 'treemacs-nerd-icons-file-face) treemacs-nerd-icons-tab)
                          :extensions (repeat)
                          :icon "")
    (treemacs-create-icon :fallback (format "%s%s" (nerd-icons-faicon "suitcase" :height 0.75 :v-adjust 0.1 :face 'treemacs-nerd-icons-file-face) treemacs-nerd-icons-tab)
                          :extensions (suitcase)
                          :icon "")
    (treemacs-create-icon :fallback (format "%s%s" (nerd-icons-material "close" :height 0.75 :v-adjust 0.1 :face 'treemacs-nerd-icons-file-face) treemacs-nerd-icons-tab)
                          :extensions (close)
                          :icon "")
    (treemacs-create-icon :fallback (format "%s%s" (nerd-icons-octicon "calendar" :height 0.75 :v-adjust 0.1 :face 'treemacs-nerd-icons-file-face) treemacs-nerd-icons-tab)
                          :extensions (calendar)
                          :icon "")
    (treemacs-create-icon :fallback (format "%s%s" (nerd-icons-faicon "briefcase" :height 0.75 :v-adjust 0.1 :face 'treemacs-nerd-icons-file-face) treemacs-nerd-icons-tab)
                          :extensions (briefcase)
                          :icon "")

    ;; file icons
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "access" :v-adjust 0 :face 'nerd-icons-red) treemacs-nerd-icons-tab) :extensions ("accdb" "accdt" "accdt") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "actionscript" :v-adjust 0 :face 'nerd-icons-red) treemacs-nerd-icons-tab) :extensions ("actionscript") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "ansible" :v-adjust 0 :face 'nerd-icons-dsilver) treemacs-nerd-icons-tab) :extensions ("ansible") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "antlr" :v-adjust 0 :face 'nerd-icons-orange) treemacs-nerd-icons-tab) :extensions ("antlr") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "asciidoc" :v-adjust 0 :face 'nerd-icons-lsilver) treemacs-nerd-icons-tab) :extensions ("asciidoc" "adoc") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "apple" :v-adjust 0 :face 'nerd-icons-lsilver) treemacs-nerd-icons-tab) :extensions ("applescript") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "appveyor" :v-adjust 0 :face 'nerd-icons-lblue) treemacs-nerd-icons-tab) :extensions ("appveyor.yml") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "arduino" :v-adjust 0 :face 'nerd-icons-dgreen) treemacs-nerd-icons-tab) :extensions ("ino" "pde") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-material "audiotrack" :v-adjust 0 :face 'nerd-icons-lblue) treemacs-nerd-icons-tab) :extensions ("mp3" "ogg" "midi" "flac" "aiff") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "babel" :v-adjust 0 :face 'nerd-icons-yellow) treemacs-nerd-icons-tab) :extensions ("babelrc" "babelignore" "babelrc.js" "babelrc.json" "babel.config.js") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "bazel" :v-adjust 0 :face 'nerd-icons-green) treemacs-nerd-icons-tab) :extensions ("bazelrc" "bazel") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "bower" :v-adjust 0 :face 'nerd-icons-orange) treemacs-nerd-icons-tab) :extensions ("bowerrc" "bower.json") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "bundler" :v-adjust 0 :face 'nerd-icons-lblue) treemacs-nerd-icons-tab) :extensions ("gemfile" "gemfile.lock") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-octicon "gear" :v-adjust 0 :face 'nerd-icons-lsilver) treemacs-nerd-icons-tab) :extensions ("bat") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "c" :v-adjust 0 :face 'nerd-icons-purple) treemacs-nerd-icons-tab) :extensions ("c" "h") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "cabal" :v-adjust 0 :face 'nerd-icons-lsilver) treemacs-nerd-icons-tab) :extensions ("cabal") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "cplusplus" :v-adjust 0 :face 'nerd-icons-purple) treemacs-nerd-icons-tab) :extensions ("cc" "cpp" "hh" "hpp" "tpp") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "clojure" :v-adjust 0 :face 'nerd-icons-blue) treemacs-nerd-icons-tab) :extensions ("clj" "cljc" "cljs" "edn") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "cmake" :v-adjust 0 :face 'nerd-icons-green) treemacs-nerd-icons-tab) :extensions ("cmake" "cmake-cache") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "cobol" :v-adjust 0 :face 'nerd-icons-dblue) treemacs-nerd-icons-tab) :extensions ("cobol") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "coffeescript" :v-adjust 0 :face 'nerd-icons-dorange) treemacs-nerd-icons-tab) :extensions ("coffeescript") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "css3" :v-adjust 0 :face 'nerd-icons-yellow) treemacs-nerd-icons-tab) :extensions ("css") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-faicon "certificate" :v-adjust 0 :face 'nerd-icons-yellow) treemacs-nerd-icons-tab) :extensions ("csr" "crt" "cer" "der" "pfx" "p12" "p7b" "p7r" "src" "crl" "sst" "stl") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-octicon "gear" :v-adjust 0 :face 'nerd-icons-lsilver) treemacs-nerd-icons-tab) :extensions ("conf" "properties" "config" "cfg" "ini" "xdefaults" "xresources" "terminalrc" "ledgerrc") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "cython" :v-adjust 0 :face 'nerd-icons-dblue) treemacs-nerd-icons-tab) :extensions ("cython") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "dart" :v-adjust 0 :face 'nerd-icons-blue-alt) treemacs-nerd-icons-tab) :extensions ("dart") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "dlang" :v-adjust 0 :face 'nerd-icons-red) treemacs-nerd-icons-tab) :extensions ("d" "dscript" "dml" "diet") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-octicon "diff" :v-adjust 0 :face 'nerd-icons-lsilver) treemacs-nerd-icons-tab) :extensions ("diff") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "dockerfile" :v-adjust 0 :face 'nerd-icons-blue) treemacs-nerd-icons-tab) :extensions ("dockerfile" "docker-compose.yml") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "editorconfig" :v-adjust 0 :face 'nerd-icons-lsilver) treemacs-nerd-icons-tab) :extensions ("editorconfig") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "elisp" :v-adjust 0 :face 'nerd-icons-purple) treemacs-nerd-icons-tab) :extensions ("el") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "elm" :v-adjust 0 :face 'nerd-icons-lgreen) treemacs-nerd-icons-tab) :extensions ("elm") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-faicon "wrench" :v-adjust 0 :face 'nerd-icons-lpurple) treemacs-nerd-icons-tab) :extensions ("envrc") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "erlang" :v-adjust 0 :face 'nerd-icons-red) treemacs-nerd-icons-tab) :extensions ("erl" "hrl") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "eslint" :v-adjust 0 :face 'nerd-icons-lpurple) treemacs-nerd-icons-tab) :extensions ("eslintrc" "eslintignore" "eslintcache") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "elixir" :v-adjust 0 :face 'nerd-icons-dpurple) treemacs-nerd-icons-tab) :extensions ("ex" "exs" "eex" "leex") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-octicon "file-binary" :v-adjust 0 :face 'nerd-icons-lsilver) treemacs-nerd-icons-tab) :extensions ("exe" "dll" "obj" "so" "o") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "cucumber" :v-adjust 0 :face 'nerd-icons-dgreen) treemacs-nerd-icons-tab) :extensions ("feature") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "fortran" :v-adjust 0 :face 'nerd-icons-lsilver) treemacs-nerd-icons-tab) :extensions ("fortran" "fortran-modern" "fortranfreeform") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "fsharp" :v-adjust 0 :face 'nerd-icons-lblue) treemacs-nerd-icons-tab) :extensions ("fsharp") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "godot" :v-adjust 0 :face 'nerd-icons-dblue) treemacs-nerd-icons-tab) :extensions ("gdscript") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-faicon "file-image-o" :v-adjust 0 :face 'nerd-icons-lblue) treemacs-nerd-icons-tab) :extensions ("gif") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "git" :height 0.85 :v-adjust 0 :face 'nerd-icons-red) treemacs-nerd-icons-tab) :extensions ("git" "gitmodules" "gitconfig" "gitignore" "gitattributes") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "go" :v-adjust 0 :face 'nerd-icons-lblue) treemacs-nerd-icons-tab) :extensions ("go") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "gradle" :v-adjust 0 :face 'nerd-icons-dblue) treemacs-nerd-icons-tab) :extensions ("gradle") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "graphql" :v-adjust 0 :face 'nerd-icons-pink) treemacs-nerd-icons-tab) :extensions ("graphql") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "haskell" :v-adjust 0 :face 'nerd-icons-silver) treemacs-nerd-icons-tab) :extensions ("hs" "lhs") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "html5" :v-adjust 0 :face 'nerd-icons-orange) treemacs-nerd-icons-tab) :extensions ("htm" "html") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "hy" :v-adjust 0 :face 'nerd-icons-dblue) treemacs-nerd-icons-tab) :extensions ("hy") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "jupyter" :v-adjust 0 :face 'nerd-icons-orange) treemacs-nerd-icons-tab) :extensions ("ipynb") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "jenkins" :v-adjust 0 :face 'nerd-icons-lsilver) treemacs-nerd-icons-tab) :extensions ("jenkins") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "jinja" :v-adjust 0 :face 'nerd-icons-dred) treemacs-nerd-icons-tab) :extensions ("j2" "jinja2") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "java" :v-adjust 0 :face 'nerd-icons-orange) treemacs-nerd-icons-tab) :extensions ("java" "jar") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "julia" :v-adjust 0 :face 'nerd-icons-green) treemacs-nerd-icons-tab) :extensions ("jl") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "javascript-badge" :v-adjust 0 :face 'nerd-icons-yellow) treemacs-nerd-icons-tab) :extensions ("js") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-faicon "code" :v-adjust 0 :face 'nerd-icons-green) treemacs-nerd-icons-tab) :extensions ("json") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "jsx" :v-adjust 0 :face 'nerd-icons-lblue) treemacs-nerd-icons-tab) :extensions ("jsx") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-material "key" :v-adjust 0 :face 'nerd-icons-yellow) treemacs-nerd-icons-tab) :extensions ("key" "pem") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "kotlin" :v-adjust 0 :face 'nerd-icons-lpurple) treemacs-nerd-icons-tab) :extensions ("kt" "kts") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-faicon "balance-scale" :v-adjust 0 :face 'nerd-icons-purple) treemacs-nerd-icons-tab) :extensions ("ledger") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "less" :v-adjust 0 :face 'nerd-icons-dblue) treemacs-nerd-icons-tab) :extensions ("less") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "lisp" :v-adjust 0 :face 'nerd-icons-red) treemacs-nerd-icons-tab) :extensions ("lisp") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-octicon "key" :v-adjust 0 :face 'nerd-icons-yellow) treemacs-nerd-icons-tab) :extensions ("license") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-material "translate" :v-adjust 0 :face 'nerd-icons-blue) treemacs-nerd-icons-tab) :extensions ("locale") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-material "lock" :v-adjust 0 :face 'nerd-icons-dred) treemacs-nerd-icons-tab) :extensions ("lock") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "lua" :v-adjust 0 :face 'nerd-icons-dblue) treemacs-nerd-icons-tab) :extensions ("lua") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "gnu" :v-adjust 0 :face 'nerd-icons-dsilver) treemacs-nerd-icons-tab) :extensions ("makefile") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "meson" :v-adjust 0 :face 'nerd-icons-green) treemacs-nerd-icons-tab) :extensions ("meson") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "ocaml" :v-adjust 0 :face 'nerd-icons-lorange) treemacs-nerd-icons-tab) :extensions ("ml" "mli" "merlin" "ocaml") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-faicon "file-video-o" :v-adjust 0 :face 'nerd-icons-lgreen) treemacs-nerd-icons-tab) :extensions ("mov" "mp4" "wav" "avi" "mkv" "webm") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "nimrod" :v-adjust 0 :face 'nerd-icons-dsilver) treemacs-nerd-icons-tab) :extensions ("nim" "nims") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "nginx" :v-adjust 0 :face 'nerd-icons-green) treemacs-nerd-icons-tab) :extensions ("nginx.conf" "nginx") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "nix" :v-adjust 0 :face 'nerd-icons-lblue) treemacs-nerd-icons-tab) :extensions ("nix") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "npm" :v-adjust 0 :face 'nerd-icons-red) treemacs-nerd-icons-tab) :extensions ("npmignore" "npmrc" "package.json" "package-lock.json" "npm-shrinwrap.json") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "delphi" :v-adjust 0 :face 'nerd-icons-red) treemacs-nerd-icons-tab) :extensions ("pascal" "objectpascal") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "patch" :v-adjust 0 :face 'nerd-icons-orange) treemacs-nerd-icons-tab) :extensions ("patch") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "perl" :v-adjust 0 :face 'nerd-icons-dblue) treemacs-nerd-icons-tab) :extensions ("perl" "pl") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "php" :v-adjust 0 :face 'nerd-icons-dblue) treemacs-nerd-icons-tab) :extensions ("php") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "phpunit" :v-adjust 0 :face 'nerd-icons-blue) treemacs-nerd-icons-tab) :extensions ("phpunit" "phpunit.xml") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "postgresql" :v-adjust 0 :face 'nerd-icons-dblue) treemacs-nerd-icons-tab) :extensions ("pgsql") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "powerpoint" :v-adjust 0 :face 'nerd-icons-orange) treemacs-nerd-icons-tab) :extensions ("pot" "potx" "potm" "pps" "ppsx" "ppsm" "ppt" "pptx" "pptm" "pa" "ppa" "ppam" "sldm" "sldx") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "sketch" :v-adjust 0 :face 'nerd-icons-lsilver) treemacs-nerd-icons-tab) :extensions ("pp") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "prolog" :v-adjust 0 :face 'nerd-icons-orange) treemacs-nerd-icons-tab) :extensions ("pro" "prolog") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "purescript" :v-adjust 0 :face 'nerd-icons-lblue) treemacs-nerd-icons-tab) :extensions ("purs") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "python" :v-adjust 0 :face 'nerd-icons-dblue) treemacs-nerd-icons-tab) :extensions ("py") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "R" :v-adjust 0 :face 'nerd-icons-dblue) treemacs-nerd-icons-tab) :extensions ("r") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "racket" :v-adjust 0 :face 'nerd-icons-dred) treemacs-nerd-icons-tab) :extensions ("racket" "rkt" "rktd" "rktl" "scrbl" "scribble" "plt") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "ruby-alt" :v-adjust 0 :face 'nerd-icons-red) treemacs-nerd-icons-tab) :extensions ("rb") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "reason" :v-adjust 0 :face 'nerd-icons-red) treemacs-nerd-icons-tab) :extensions ("re" "rei") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "rust" :v-adjust 0 :face 'nerd-icons-red) treemacs-nerd-icons-tab) :extensions ("rs") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "sbt" :v-adjust 0 :face 'nerd-icons-dsilver) treemacs-nerd-icons-tab) :extensions ("sbt") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "sass" :v-adjust 0 :face 'nerd-icons-lpink) treemacs-nerd-icons-tab) :extensions ("scss" "sass") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "scala" :v-adjust 0 :face 'nerd-icons-red) treemacs-nerd-icons-tab) :extensions ("scala") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-faicon "database" :v-adjust 0 :face 'nerd-icons-yellow) treemacs-nerd-icons-tab) :extensions ("sql") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "sqlite" :v-adjust 0 :face 'nerd-icons-blue) treemacs-nerd-icons-tab) :extensions ("sqlite" "db3" "sqlite3") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "svg" :v-adjust 0 :face 'nerd-icons-orange) treemacs-nerd-icons-tab) :extensions ("svg") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "swagger" :v-adjust 0 :face 'nerd-icons-green) treemacs-nerd-icons-tab) :extensions ("swagger") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "swift" :v-adjust 0 :face 'nerd-icons-orange) treemacs-nerd-icons-tab) :extensions ("swift") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "terminal" :v-adjust 0 :face 'nerd-icons-dgreen) treemacs-nerd-icons-tab) :extensions ("sh" "bash" "zsh" "fish" "zshrc" "bashrc") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "verilog" :v-adjust 0 :face 'nerd-icons-dblue) treemacs-nerd-icons-tab) :extensions ("sv" "v") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "tex" :v-adjust 0 :face 'nerd-icons-dsilver) treemacs-nerd-icons-tab) :extensions ("tex") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "terraform" :v-adjust 0 :face 'nerd-icons-dsilver) treemacs-nerd-icons-tab) :extensions ("tf" "tfvars") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "typescript-alt" :v-adjust 0 :face 'nerd-icons-blue) treemacs-nerd-icons-tab) :extensions ("ts") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "tsx-alt" :v-adjust 0 :face 'nerd-icons-lgreen) treemacs-nerd-icons-tab) :extensions ("tsx") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "vagrant" :v-adjust 0 :face 'nerd-icons-blue) treemacs-nerd-icons-tab) :extensions ("vagrantfile") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "vue" :v-adjust 0 :face 'nerd-icons-green) treemacs-nerd-icons-tab) :extensions ("vue") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "excel" :v-adjust 0 :face 'nerd-icons-green) treemacs-nerd-icons-tab) :extensions ("xls" "xlsx" "xlsm" "ods" "fods") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "wasm" :v-adjust 0 :face 'nerd-icons-lpurple) treemacs-nerd-icons-tab) :extensions ("wasm" "wat") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-faicon "font" :v-adjust 0 :face 'nerd-icons-lsilver) treemacs-nerd-icons-tab) :extensions ("woff" "woff2" "ttf" "otf" "eot" "pfa" "pfb" "sfd") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-octicon "code" :v-adjust 0 :face 'nerd-icons-lpurple) treemacs-nerd-icons-tab) :extensions ("xml" "xsl") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-octicon "code" :v-adjust 0 :face 'nerd-icons-yellow) treemacs-nerd-icons-tab) :extensions ("yaml" "yml") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "yarn" :v-adjust 0 :face 'nerd-icons-dblue) treemacs-nerd-icons-tab) :extensions ("yarn.lock" "yarnrc" "yarnclean" "yarn-integrity" "yarn-metadata.json" "yarnignore") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-fileicon "R" :v-adjust 0 :face 'nerd-icons-dblue) treemacs-nerd-icons-tab) :extensions ("r") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-octicon "file-media" :v-adjust 0 :face 'nerd-icons-orange) treemacs-nerd-icons-tab)
                          :extensions ("png" "jpg" "jpeg" "ico" "tif" "tiff" "bmp" "psd" "ai" "eps" "indd" "webp") :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-octicon "file-code" :v-adjust 0 :face 'treemacs-nerd-icons-file-face) treemacs-nerd-icons-tab)
                          :extensions ("cask" "csv" "cxx" "ideavimrc" "inputrc" "pm"
                                       "pm6" "scm " "sql" "styles" "toml" "tridactylrc" "vh" "vimperatorrc"
                                       "vimrc" "vrapperrc")
                          :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-octicon "book" :v-adjust 0 :face 'treemacs-nerd-icons-file-face) treemacs-nerd-icons-tab)
                          :extensions ("lrf" "lrx" "cbr" "cbz" "cb7" "cbt" "cba" "chm" "djvu"
                                       "doc" "docx" "pdb" "pdb" "fb2" "xeb" "ceb" "inf" "azw"
                                       "azw3" "kf8" "kfx" "lit" "prc" "mobi" "exe" "or"
                                       "pkg" "opf" "txt" "pdb" "ps" "rtf" "pdg" "xml" "tr2"
                                       "tr3" "oxps" "xps")
                          :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-octicon "file-text" :v-adjust 0 :face 'treemacs-nerd-icons-file-face) treemacs-nerd-icons-tab)
                          :extensions ("md" "markdown" "rst" "log" "org" "txt"
                                       "CONTRIBUTE" "LICENSE" "README" "CHANGELOG")
                          :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-octicon "file-binary" :v-adjust 0 :face 'treemacs-nerd-icons-file-face) treemacs-nerd-icons-tab)
                          :extensions ("class" "exe" "dll" "obj" "so" "o" "out" "elc" "pyc")
                          :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-octicon "file-pdf" :v-adjust 0 :face 'nerd-icons-orange) treemacs-nerd-icons-tab)
                          :extensions ("pdf")
                          :icon "")
    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-octicon "file-zip" :v-adjust 0 :face 'treemacs-nerd-icons-file-face) treemacs-nerd-icons-tab)
                          :extensions ("zip" "7z" "tar" "gz" "rar" "tgz")
                          :icon "")

    (treemacs-create-icon :fallback (format "  %s%s" (nerd-icons-octicon "file-text" :v-adjust 0 :face 'treemacs-nerd-icons-file-face) treemacs-nerd-icons-tab)
                          :extensions (fallback)
                          :icon "")))

(provide 'nerd-icons-treemacs-theme)
;;; nerd-icons-treemacs-theme.el ends here
